trigger:
- '*'

variables:
- group: Release

stages:
- stage: 'Build'
  displayName: 'Build and Push'
  jobs:  
  - job: 'Build'
    displayName: 'Build job'
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - publish: '$(Build.SourcesDirectory)/manifests'
      artifact: manifests
