apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-deploy-stage
  labels:
    service: es-deploy-stage
  namespace: graylog-stage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: es-deploy-stage
    spec:
      # affinity:
      #   podAntiAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: service
      #           operator: In
      #           values:
      #           - es-deploy-stage
      #       topologyKey: "kubernetes.io/hostname"
      initContainers:
      - name: init-sysctl
        image: busybox:1.30
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:6.7.2
        readinessProbe:
          tcpSocket:
            port: 9201
          initialDelaySeconds: 20
          periodSeconds: 30
        ports:
        - containerPort: 9201
        - containerPort: 9301
      nodeSelector:
        agentpool: graylog
---
apiVersion: v1
kind: Service
metadata:
  name: es6-stage
  namespace: graylog-stage
spec:
  type: NodePort
  selector:
    service: es-deploy-stage
  ports:
  - name: "9201"
    port: 9201
    targetPort: 9201
    nodePort: 30001
  - name: "9301"
    port: 9301
    targetPort: 9301
    nodePort: 30002
