apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deploy-stage
  labels:
    service: mongo-deploy-stage
  namespace: graylog-stage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo-deploy-stage
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27018
      nodeSelector:
        agentpool: graylog 

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-stage
  namespace: graylog-stage
spec:
  selector:
    service: mongo-deploy-stage
  ports:
  - name: "27018"
    port: 27018
    targetPort: 27018    
