apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mongo-deploy-dev
  labels:
    service: mongo-deploy-dev
  namespace: graylog-dev
spec:
  replicas: 1
  template:
    metadata:
      labels:
        service: mongo-deploy-dev
    spec:
      containers:
      - name: mongodb
        image: mongo:3
        ports:
        - containerPort: 27017
      nodeSelector:
        agentpool: graylog 

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-dev
  namespace: graylog-dev
spec:
  selector:
    service: mongo-deploy-dev
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017      
