apiVersion : apps/v1
kind: Deployment
metadata:
  name: web
  namespace: webapp-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: acrmmhddofogbaic.azurecr.io/web
          ports:
          - containerPort: 80
      nodeSelector:
        agentpool: webapp
---
apiVersion : apps/v1
kind: Deployment
metadata:
  name: leaderboard
  namespace: webapp-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: leaderboard
  template:
    metadata:
      labels:
        app: leaderboard
    spec:
      containers:
        - name: leaderboard
          image: acrmmhddofogbaic.azurecr.io/leaderboard
          ports:
          - containerPort: 80
      nodeSelector:
        agentpool: webapp