apiVersion: v1
kind: Service
metadata:
    name: leaderboard
    namespace: webapp-stage
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: leaderboard
---
apiVersion: v1
kind: Service
metadata:
    name: web
    namespace: webapp-stage
spec:
    type: LoadBalancer
    ports:
    - port: 80 
    selector:
        app: web
